_target_: examples.nllb.mining.global_mining.modules.preprocess.mlenc_sentence_encoder.MLEncTextEncoder

_name: laser3_encoder
encoder_model: null
spm_model: null
spm_vocab: null
max_sentences:
max_tokens: 12_000
stable_sort: False
normalize: False
fp16_storage: False
cpu: False
