_target_: examples.nllb.mining.global_mining.modules.preprocess.mlenc_sentence_encoder.MLEncTextEncoder

_name: laser2
encoder_model: ???
spm_model: ???
max_sentences:
max_tokens: 12_000
stable_sort: False
normalize: False
fp16_storage: True
cpu: False
